on:
   push:
     branches: main

jobs:
  prep-output:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr

      - name: Check out repository
        uses: actions/checkout@v4

      - name: List files
        run: Rscript -e 'source("list_files.R")'

      - name: Commit results
        run: |
          git config --local user.email "techlab@nisra.gov.uk"
          git config --local user.name "NISRA-Tech-Lab"
          git add file_list.txt
          git commit -m 'File list updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
